# Generated by Django 4.2.10 on 2024-02-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_crud_operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee_details',
        ),
        migrations.AlterModelTable(
            name='employee_details',
            table='Employee_details',
        ),
    ]
